### ISSUE TITLE
Validations for active storage

### ISSUE THREAD

**Issue by vbrazo** [richardvenneman/trestle-active_storage#23]
My app needs to be able to limit the file size to 700KB and we should accept only the following formats: JPG, GIF, PNG.

I noticed that there is a good gem that handles these kind of validations: https://github.com/igorkasyanchuk/active_storage_validations. What do you think about integrating this gem?

**Comment by vbrazo** [comment]
Looks like they're trying to add this gem to the Rails core project: https://github.com/rails/rails/issues/33741

**Comment by richardvenneman** [comment]
Hi @vbrazo,

Thanks, I noticed that feature is coming to Rails as well. That would definitely be the preferred way to support validations. I think it will work out of the box but this should definitely be tested before Rails 6 will be released. I will keep this issue open for that :+1:.

**Comment by richardvenneman** [comment]
@vbrazo I can confirm that [active_storage_validations](https://github.com/igorkasyanchuk/active_storage_validations) is great and is compatible with this gem out-of-the-box.

**Comment by vbrazo** [comment]
Thanks man

**Comment by gitjul** [comment]
I ran into an issue and I'm not entirely sure if it's trestle-active_storage or trestle itself.
there's a way to save a record with no attachments even with a presence validation. the validation works if you're trying to save a newly added record and adding attachments for the first time (or rather not adding any and wanting to save). but when you successfully save a record, and then delete all the attachments and save, it's successfully saved, even though the record is invalid (and you can check that in rails console ofc with `the_saved_record.valid?` which is `false`).

can you tell me if this is a known issue and if you know a fix for this? let me know if I should open a new one, and whether here or in trestle https://github.com/TrestleAdmin/trestle. thx!

PS thanks for the gem! 💎

**Comment by gitjul** [comment]
ooops, now I think this may rather be a problem with the active_storage_validations gem, so I probably wrote in the wrong place :)
