### ISSUE TITLE
has_many_attached

### ISSUE THREAD

**Issue by metronom72** [richardvenneman/trestle-active_storage#28]
Is this gem implement images form `has_many_attached`

and how to use it?

**Comment by richardvenneman** [comment]
Hi @metronom72, definitely. You should just be able to use the `active_storage_field` macro like this:

```ruby
active_storage_field :avatar
active_storage_field :photos
```

Let me know if that works for you.

**Comment by metronom72** [comment]
Well, I had tried :)

my file has next lines
```
  active_storage_fields do
    [:images]
  end

  form do |pack|
    active_storage_field :images
    ...
  end
```

but I can add only first image. And on the update this image will be replaced with new one

**Comment by metronom72** [comment]
@richardvenneman that's my fault. Let me close this issu :)

**Comment by lphm** [comment]
I reopen this issue because for me it does not work for ` has_many_attached :attachments`
`
active_storage_fields do
    [:attachments]
  end
`
`
  form do |record|
      active_storage_field :attachments
end
`
And only one file is saved (and replace existing files)
