### ISSUE TITLE
Resource form cannot be re-displayed if attachment failed to save due to validation error

### ISSUE THREAD

**Issue by oleg-kiviljov** [richardvenneman/trestle-active_storage#71]
The problem lies in _has_many_field.html.erb partial implementation, it tries to show the delete link even if attachment has not been persisted. It would be more logical to check if attachment is persisted? before displaying the delete link and download link.

**Comment by oleg-kiviljov** [comment]
Hi @richardvenneman can you please review this PR?

**Comment by richardvenneman** [comment]
Hi @oleg-kiviljov, sorry for the extreme delay. Thanks for the report and your contribution! I've just merged it and released a new version (3.0.1).
